spring:
  application:
    name: target-server

  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver

# Server
server:
  port: 8080

# Logging
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

